services:
  pgsql:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local