networks:
  simple-crud:
    driver: bridge

services:
  go-app:
    container_name: simple-crud-app
    restart: always
    image: phrp/simple-crud:1.0
    build: .
    environment:
      DATABASE_URL: "host=pgsql user=${DB_USERNAME} password=${DB_PASSWORD:-secret} dbname=${DB_NAME} sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - simple-crud
    depends_on:
      - pgsql

  pgsql:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    networks:
      - simple-crud
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local